Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,5 +1,6 @@
 name: test
 on: [push, workflow_dispatch]
+
 jobs:
   test:
     runs-on: ubuntu-24.04
@@ -28,8 +29,13 @@ jobs:
           cd test
           make clean
           make
-          # make will return success even if the test fails, so check for failure in the results.xml
-          ! grep failure results.xml
+          # Check for failures in results.xml without failing if grep finds nothing
+          if grep -q "failure" results.xml; then
+            echo "Test failed."
+            exit 1
+          else
+            echo "All tests passed."
+          fi
 
       - name: Test Summary
         uses: test-summary/action@v2.3
